import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from "@/context/client-provider"
import { getAuthSession } from '@/lib/nextauth'
import Header from '@/components/header'
import Footer from '@/components/footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getAuthSession();
  return (
    <html lang="fr">

      <body className={inter.className}>
      <Provider session={session}>
      <Header />
        {children}
      <Footer />
      </Provider>
      </body>

    </html>
  )
}
